config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get 'welcome/index'

  resources :docs

  authenticated :user do 
    root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/doc.rb
class Doc < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

	before_action :find_doc, only: [:show, :edit, :update, :destroy]

	def index
		@docs = Doc.where(user_id: current_user)
	end

	def show
	end

	def new
		@doc = current_user.docs.build

	end

	# Does not have a view for itself
	def create
		@doc = current_user.docs.build(doc_params)

		if @doc.save
			redirect_to @doc #redirect refreshes page, input lost
		else
			render 'new' # keeps input, ready to reattempt save
		end
	end

	# Only responsible for view file.
	def edit
	end

	# Does not have a view itself. Makes changes to databse through edit view.
	# Fetches doc with the before action and then change the params and updates the doc.
	def update
		if @doc.update(doc_params)
			redirect_to @doc
		else
			render 'edit' # Again renders retains filled fields
		end
	end

	def destroy
		@doc.destroy
		redirect_to docs_path
	end

	private

	def find_doc
		@doc = Doc.find(params[:id])
	end

	def doc_params
		# Requires the Doc model and permit two attributes
		params.require(:doc).permit(:title, :content)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/docs/edit.html.erb
<h1> Fix Doc! </h1>

<%= render 'form' %>
<%= link_to "Cancel", doc_path %>

app/views/docs/index.html.erb
<% @docs.each do |doc| %>
<h2><%= link_to doc.title, doc %></h2>
<p><%= time_ago_in_words(doc.created_at) %></p>
<p><%= truncate(doc.content, length: 50) %></p>
<% end %>

<button><%= link_to "Create Document", new_doc_path %></button>

app/views/docs/new.html.erb
<h1> New Doc! </h1>

<%= render 'form' %>

app/views/docs/show.html.erb
<h1><%= @doc.title %></h1>
<p><%= @doc.content %></p>

<%= link_to "All Documents", docs_path %>
<%= link_to "Fix Document", edit_doc_path(@doc) %>
<%= link_to "Trash It", doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileCabinet | Your Life's Work </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="header_inner">
			<%= link_to "FileCabinet", root_path, id: "logo" %>
			<nav>
				<% if user_signed_in? %>
					<%= link_to "Create Document", new_doc_path %>
					<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
				<% else %>
					<%= link_to "Log In", new_user_session_path %>
				<% end %>		
			</nav>
		</div>
	</header>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	
	<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div id="banner">
	<div class="banner_content">
		<h1>FileCabinet</h1>
		<p>Your life's work. Organised, always.</p>
		<button><%= link_to "Enter", new_user_registration_path %></button>
	</div>
</div>

<div id="callouts">
	<div class="callout_inner">
		<div class="wrapper">
			<div class="callout">
				<h2>Organise</h2>
				<p> Create an account. Create documents. Simple.</p>
			</div>
		</div>
	</div>
</div>

<div id="bottom_cta">
	<div class="wrapper">
		<h2>Go Ahead!</h2>
		<br>
		<button><%= link_to "Join Now", new_user_registration_path %></button>
	</div>
</div>